In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
df=pd.read_csv('ex1data1.txt',sep=",", header=None)
df.columns=["X","Y"]
df.head()

X        Y
0  6.1101  17.5920
1  5.5277   9.1302
2  8.5186  13.6620
3  7.0032  11.8540
4  5.8598   6.8233

In [28]:
df['bias']=1

In [29]:
df.head()

X        Y  bias
0  6.1101  17.5920     1
1  5.5277   9.1302     1
2  8.5186  13.6620     1
3  7.0032  11.8540     1
4  5.8598   6.8233     1

In [30]:
x=df[['bias','X']]
y=df['Y']

AttributeError: 'Series' object has no attribute 'reshape'

Part 3: Cost and Gradient Descent

In [60]:
m=len(y)
print(m)

97


In [109]:
X=np.array(x)

In [110]:
Y=np.array(y)

In [111]:
print(Y)

[17.592    9.1302  13.662   11.854    6.8233  11.886    4.3483  12.
  6.5987   3.8166   3.2522  15.505    3.1551   7.2258   0.71618  3.5129
  5.3048   0.56077  3.6518   5.3893   3.1386  21.767    4.263    5.1875
  3.0825  22.638   13.501    7.0467  14.692   24.147   -1.22     5.9966
 12.134    1.8495   6.5426   4.5623   4.1164   3.3928  10.117    5.4974
  0.55657  3.9115   5.3854   2.4406   6.7318   1.0463   5.1337   1.844
  8.0043   1.0179   6.7504   1.8396   4.2885   4.9981   1.4233  -1.4211
  2.4756   4.6042   3.9624   5.4141   5.1694  -0.74279 17.929   12.054
 17.054    4.8852   5.7442   7.7754   1.0173  20.992    6.6799   4.0259
  1.2784   3.3411  -2.6807   0.29678  3.8845   5.7014   6.7526   2.0576
  0.47953  0.20421  0.67861  7.5435   5.3436   4.2415   6.7981   0.92695
  0.152    2.8214   1.8451   4.2959   7.2029   1.9869   0.14454  9.0551
  0.61705]


In [112]:
h=np.dot(X,theta)
print(h)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [115]:
h.shape

(97, 1)

In [121]:
Y=Y.reshape(97,1)

In [122]:
t=np.subtract(h,Y)
print(t)

[[-17.592  ]
 [ -9.1302 ]
 [-13.662  ]
 [-11.854  ]
 [ -6.8233 ]
 [-11.886  ]
 [ -4.3483 ]
 [-12.     ]
 [ -6.5987 ]
 [ -3.8166 ]
 [ -3.2522 ]
 [-15.505  ]
 [ -3.1551 ]
 [ -7.2258 ]
 [ -0.71618]
 [ -3.5129 ]
 [ -5.3048 ]
 [ -0.56077]
 [ -3.6518 ]
 [ -5.3893 ]
 [ -3.1386 ]
 [-21.767  ]
 [ -4.263  ]
 [ -5.1875 ]
 [ -3.0825 ]
 [-22.638  ]
 [-13.501  ]
 [ -7.0467 ]
 [-14.692  ]
 [-24.147  ]
 [  1.22   ]
 [ -5.9966 ]
 [-12.134  ]
 [ -1.8495 ]
 [ -6.5426 ]
 [ -4.5623 ]
 [ -4.1164 ]
 [ -3.3928 ]
 [-10.117  ]
 [ -5.4974 ]
 [ -0.55657]
 [ -3.9115 ]
 [ -5.3854 ]
 [ -2.4406 ]
 [ -6.7318 ]
 [ -1.0463 ]
 [ -5.1337 ]
 [ -1.844  ]
 [ -8.0043 ]
 [ -1.0179 ]
 [ -6.7504 ]
 [ -1.8396 ]
 [ -4.2885 ]
 [ -4.9981 ]
 [ -1.4233 ]
 [  1.4211 ]
 [ -2.4756 ]
 [ -4.6042 ]
 [ -3.9624 ]
 [ -5.4141 ]
 [ -5.1694 ]
 [  0.74279]
 [-17.929  ]
 [-12.054  ]
 [-17.054  ]
 [ -4.8852 ]
 [ -5.7442 ]
 [ -7.7754 ]
 [ -1.0173 ]
 [-20.992  ]
 [ -6.6799 ]
 [ -4.0259 ]
 [ -1.2784 ]
 [ -3.3411 ]
 [  2.6807 ]
 [ -0.29678]
 [ -3.8845 ]

In [123]:
t.shape

(97, 1)

In [132]:
theta0=0
theta1=0
theta=[[theta0],[theta1]]
print(theta)

[[0], [0]]


In [64]:
len(theta)

2

In [65]:
ans=0

Intial cost computed with thetas intialised to 0

In [66]:
for i in range(97):
    sum=theta0*1 +theta1*X[i][1]
    sum=sum-Y[i]
    prod=sum*sum
    ans=ans+prod
    

In [67]:
ans/(2*m)

32.072733877455654

In [134]:
print(Y[0][0])

17.592


In [135]:
alpha=0.01
for i in range(1500):
    ans1=0
    ans2=0
    sum=0
    for j in range(97):
        sum=theta0*1 + theta1*X[j][1]
        sum=sum-Y[j][0]
        ans1=ans1+sum
    temp0=theta0- (alpha/m)*(ans1)
    sum=0 
    for j in range(97):
         sum=theta0*1+theta1*X[j][1]
         sum=sum-Y[j]
         prod=sum*X[j][1]
         ans2=ans2+prod
    temp1=theta1-(alpha/m)*ans2   
    theta0=temp0
    theta1=temp1 
        
          

In [136]:
theta0

array([-3.63029144])

In [137]:
theta1

array([1.16636235])